num1 = int(input("Введите первое число: "))
num2 = int(input("Введите второе число: "))
print (num1 + num2)
print (num1 - num2)
print (num1 * num2)
print (num1 / num2)
number = int(input("Введите число:"))
divisor = int(input("Введите делитель:"))
remainder = number % divisor
print ("Остаток от деления:", remainder)
base = float(input("Введите число: "))
exponent = int(input("Введите показатель степени: "))
result = base ** exponent
print (base ** exponent)
num1 = int(input("Введите первое число: "))
num2 = int(input("Введите второе число: "))
print ("Большее число:", max (num1, num2))
first_name = input("Введите имя: ")
last_name = input("Введите фамилию: ")
full_name = first_name + last_name
print("Полное имя:", full_name)
print("Длина имени:", len(full_name))
print("Полное имя:", full_name)
age = int(input("Введите ваш возраст: "))
print("Через 5 лет: ", age + 5)
print("Через 10 лет: ", age + 10)
print("Через 20 лет: ", age + 10)
kzt = int(input("Введите сумму в тенге: ")) 
kurs = float(input("Введите курс доллара: "))
print (kzt / kurs)
length = int(input("Введите длину: "))
width = int(input("Введите ширину: "))
print("Площадь: ", (length * width))
print("Периметр: ", (2 * (length * width)))
age = int(input("Введите ваш возраст: "))
if age >=18: print("Вы можете голосовать!")
else:
    print("Вам еще рано голосовать")