password = input("Введите тект:")
print("1. В верхнем регистре:", password.upper())
print("2. В нижнем регистре:", password.lower())
print("3. С первой заглавной буквой:", password.capitalize())
print("4. Каждое слово с заглавной буквы:", password.title())
s = input("Введите строку: ")
print(s.isalpha())
print(s.isdigit())
print(len(s))
sentense = input("Введите предложение:")
old_word = input("Введите слово для замены: ")
new_word = input("Введите новое слово: ")
print(sentense.replace(old_word, new_word))
print(sentense.count('old_word'))
text = input("Введите несколько слов через пробел: ")
words = text.split()
print("Список слов:", words)
print("Количество слов:", len(text))
text = input("Введите несколько слов через пробел: ")
words = text.split()
joined_text = "-".join(words)
print("Результат:", joined_text)
filename = input("Введите имя файла: ")
if filename.lower().startswith('а'):
    print('Имя начинается на А')
elif filename.lower().endswith('txt'):
    print('Имя заканчивается на txt')
else:
    print('Имя НЕ заканчивается на txt')
students = ["Аня", "Дидар", "Лера", "Коля", "Маша"]
print(f'Студентов: {len(students)}')
students.append('Марк')
students.extend(['Данияр', 'Мика'])
print(f'Студентов: {len(students)}')
fruits = ['яблоко', 'банан', 'апельсин', 'груша', 'банан']
print(f'fruits" ')
position = fruits('апельсин')
print(position)
how_many = fruits.count('банан')
print(how_many)
fruits.remove('банан')
print(f'fruits" ')
numbers = [5, 2, 9, 1, 7, 3]
print("numbers")
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
letters = ['А', 'Б', 'Г', 'Д']
print("letters")
letters.insert(2, 'В')
print("letters")
letters.pop(1)
print("letters")
sentence = input("Введите предложение со словами через пробел: ")
print(sentense.lower())
result = sentense.split(' ')
words = sentence_lower.split()
words.sort()
print("words")
result = ','.join(words)
print(result)