password = input("Введите тект:")
print("1. В верхнем регистре:", text.upper())
print("2. В нижнем регистре:", text.lower())
print("3. С первой заглавной буквой:", text.capitalize())
print("4. Каждое слово с заглавной буквы:", text.title())
s = input("Введите строку: ")
print(s.isalpha())
print(s.isdigit())
print(len(s))
sentense = input("Введите предложение:")
old_word = input("Введите слово для замены: ")
new_word = input("Введите новое слово: ")
print(text.replace("sentense", 'old_word'))
print(text.count('old_word'))
text = input("Введите несколько слов через пробел: ")
words = text.split()
print("Список слов:", words)
print("Количество слов:", len(text))
text = input("Введите несколько слов через пробел: ")
words = text.split()
joined_text = "-".join(words)
print("Результат:", joined_text)
filename = input("Введите имя файла: ")
if name.lower().startswith('а'):
    print('Имя начинается на А')
elif name.lower().endswith('txt'):
    print('Имя заканчивается на txt')  # Печатает
else:
    print('Имя НЕ заканчивается на txt')
students = ["Аня", "Дидар", "Лера", "Коля", "Маша"]
print(f'Студентов: {len(students)}')
students.append('Марк')
students.extend(['Данияр', 'Мика'])
print(f'Студентов: {len(students)}')
fruits = ['яблоко', 'банан', 'апельсин', 'груша', 'банан']
print(f'fruits" ')
position = fruits('апельсин')
print(position)
how_many = fruits.count('банан')
print(how_many)
fruits.remove('банан')
print(f'fruits" ')
numbers = [5, 2, 9, 1, 7, 3]
print("numbers")
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
letters = ['А', 'Б', 'Г', 'Д']
print("letters")
letters.insert(2, 'В')
print("letters")
letters.pop(1)
print("letters")
sentence = input("Введите предложение со словами через пробел: ")
print(name.lower())
result = sentense.split(' ')
words = sentence_lower.split()
words.sort()
print("words")
result = ','.join(words)
print(result)